"""create users, user_reports, tasks tables

Revision ID: 80cdebebf776
Revises: 
Create Date: 2026-08-02 14:36:55.857561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80cdebebf776'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('user_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('intent', sa.Enum('greeting', 'research_topic', 'unsupported', name='intent_enum'), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'classifying', 'planning', 'researching', 'synthesizing', 'done', 'failed', name='run_status_enum'), nullable=False),
    sa.Column('strategy_summary', sa.Text(), nullable=True),
    sa.Column('report_title', sa.Text(), nullable=True),
    sa.Column('report_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_reports_user_id'), 'user_reports', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('depends_on', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'failed', name='task_status_enum'), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['user_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'report_id')
    )
    op.create_index(op.f('ix_tasks_report_id'), 'tasks', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_report_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_user_reports_user_id'), table_name='user_reports')
    op.drop_table('user_reports')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
