"""add message_id to reports table

Revision ID: 883ba7004106
Revises: c70ef5169ac7
Create Date: 2026-08-22 00:48:35.375803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '883ba7004106'
down_revision: Union[str, Sequence[str], None] = 'c70ef5169ac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_reports', sa.Column('message_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'user_reports', ['message_id'])
    op.create_foreign_key(None, 'user_reports', 'messages', ['message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_reports', type_='foreignkey')
    op.drop_constraint(None, 'user_reports', type_='unique')
    op.drop_column('user_reports', 'message_id')
    # ### end Alembic commands ###
